export type LineCodingScheme =
  | 'Unipolar NRZ'
  | 'Polar NRZ-L'
  | 'Polar NRZ-I'
  | 'RZ'
  | 'Manchester'
  | 'Differential Manchester'
  | 'AMI'
  | 'Pseudoternary'
  | 'MLT-3'
  | '2B1Q';

export interface EducationalContent {
  explanation: string;
  generation: string;
  applications: string;
  insights: string;
  mistakes: string;
  takeaways: string;
}

export const educationalData: Record<string, EducationalContent> = {
  'Unipolar NRZ': {
    explanation: "NRZ or Non-Return to Zero is a unipolar line coding scheme. Here data bit 0 presents voltage 0 and data bit 1 represents positive voltage. The signal does not return to zero at the middle of time T for the bit, hence it is called NRZ.",
    generation: "Generated by mapping '1' to +V and '0' to 0V. The voltage level remains constant throughout the entire bit duration.",
    applications: "Used in very short-distance communication and basic digital logic circuits (like SPI/I2C at chip level) where clock synchronization is handled by a separate clock line.",
    insights: "It has a high DC component and lacks self-synchronization. Long strings of 1s or 0s cause loss of synchronization at the receiver.",
    mistakes: "Mistaking it for a self-clocking signal. Forgetting that a long sequence of 1s will cause the receiver's clock to drift.",
    takeaways: "Simplest form of line coding, uses only positive voltage and zero. 'Non-Return to Zero' means the signal stays at its level for the full bit period."
  },
  'Polar NRZ-L': {
    explanation: "In Polar NRZ-L (Level), the voltage level determines the value of the bit. Generally, bit 0 represents logic high/positive voltage and bit 1 represents logic low/negative voltage.",
    generation: "Generated by mapping '0' to +V and '1' to -V. It uses both positive and negative voltages, hence 'Polar'.",
    applications: "RS-232 serial communication (though RS-232 uses negative logic). Used in basic baseband transmission where simplicity is preferred.",
    insights: "Using two non-zero voltages (polar) reduces the average power compared to unipolar if 1s and 0s are equally likely. Still suffers from DC component issues.",
    mistakes: "Confusing NRZ-L with Unipolar NRZ. In Polar NRZ-L, 0V is not used for data; it strictly uses +V and -V.",
    takeaways: "Polar NRZ-L uses level to represent bits (0 = +V, 1 = -V). It lacks self-synchronization for long strings of 0s or 1s."
  },
  'Polar NRZ-I': {
    explanation: "In NRZ-I (Invert), the signal alternates for bit 1, and for bit 0 the signal stream remains as it is. A transition at the beginning of the bit time indicates a 1, and no transition indicates a 0.",
    generation: "Generated by checking the incoming bit. If it's a '1', invert the current voltage level. If it's a '0', keep the current voltage level.",
    applications: "Used in Fast Ethernet (100Base-FX) and USB signaling, often in combination with block coding like 4B/5B to prevent long strings of 0s.",
    insights: "Solves the synchronization problem for long strings of 1s (because every 1 causes a transition), but long strings of 0s still cause synchronization issues.",
    mistakes: "Thinking NRZ-I depends on the absolute voltage level. It depends ONLY on whether a transition occurs at the start of the bit.",
    takeaways: "Transition = 1, No Transition = 0. Differential encoding makes it robust against polarity reversal of the twisted pair cables."
  },
  'RZ': {
    explanation: "In Polar RZ (Return to Zero), the signal returns to zero at T/2 duration of the signal for both bit 1 & 0. Bit 1 = +V and bit 0 = -V.",
    generation: "For a '1', the signal goes to +V for the first half of the bit, then returns to 0V. For a '0', it goes to -V for the first half, then returns to 0V.",
    applications: "Baseband data transmission where self-clocking is strictly required, though it is largely replaced by Manchester due to bandwidth inefficiency.",
    insights: "The return to zero in the middle of every bit guarantees a transition, providing excellent self-clocking. However, it requires twice the bandwidth of NRZ.",
    mistakes: "Confusing it with Unipolar RZ. Polar RZ uses 3 voltage levels (+V, 0, -V), while Unipolar RZ uses only 2 (+V, 0).",
    takeaways: "Every bit has a transition back to zero in the middle. Excellent synchronization but poor bandwidth utilization."
  },
  'Manchester': {
    explanation: "Manchester coding uses a transition in the middle of every bit period for synchronization. Usually, a high-to-low transition means '0' and a low-to-high transition means '1'.",
    generation: "XOR the data bit with a clock signal. '0' translates to +V then -V. '1' translates to -V then +V.",
    applications: "Used universally in 10Base-T Ethernet (Classic Ethernet) and RFID tags.",
    insights: "Always has a transition in the middle of the bit, ensuring perfect self-synchronization and eliminating the DC component completely.",
    mistakes: "Getting the transition direction swapped. Different standards (IEEE 802.3 vs G.E. Thomas) define 0 and 1 in opposite directions.",
    takeaways: "Mid-bit transition acts as both data and clock. No DC component. Requires double the bandwidth of NRZ."
  },
  'Differential Manchester': {
    explanation: "In Differential Manchester, there is always a transition in the middle of the bit. If the next bit is 1, there is NO transition at the start of the bit. If the next bit is 0, there IS a transition at the start of the bit.",
    generation: "Middle transition is always present. Start transition depends on data: '0' causes an inversion at the start, '1' causes no inversion.",
    applications: "Used in IEEE 802.5 Token Ring networks.",
    insights: "Combines the benefits of Manchester (no DC component, self-clocking) with the benefits of differential encoding (immunity to wire polarity reversal).",
    mistakes: "Missing the mid-bit transition. Remember: D-Manchester ALWAYS transitions in the middle; the data is encoded in the START transition.",
    takeaways: "Bit 0 = Transition at start. Bit 1 = No transition at start. Both have mid-bit transitions."
  },
  'AMI': {
    explanation: "Alternate Mark Inversion (AMI) is a Bipolar scheme. Bit 0 represents zero voltage, and bit 1 alternates between positive and negative voltage.",
    generation: "When a '0' arrives, output 0V. When a '1' arrives, output +V or -V, alternating from the last non-zero voltage used.",
    applications: "Used in traditional T1 and E1 telecom lines.",
    insights: "Alternating 1s eliminate the DC component. However, a long string of 0s will produce a flat 0V line, losing synchronization (handled by scrambling techniques like B8ZS).",
    mistakes: "Forgetting to alternate the 1s. If the last '1' was +V, the next '1' MUST be -V, otherwise it's a bipolar violation.",
    takeaways: "Mark (1) alternates polarity. Space (0) is zero voltage. Built-in error detection because two consecutive pulses of the same polarity indicate an error."
  },
  'Pseudoternary': {
    explanation: "Pseudoternary is the opposite of the AMI scheme. Bit 1 represents zero voltage, and bit 0 alternates between positive and negative voltage.",
    generation: "When a '1' arrives, output 0V. When a '0' arrives, output +V or -V, alternating from the last non-zero voltage.",
    applications: "Used in ISDN (Integrated Services Digital Network) basic rate interfaces.",
    insights: "Has the same advantages and disadvantages as AMI. Long strings of 1s will cause a loss of synchronization instead of 0s.",
    mistakes: "Confusing it with AMI. Remember: Pseudoternary alternates on 0s, AMI alternates on 1s.",
    takeaways: "Alternates on '0'. '1' is 0V. Same bandwidth and DC characteristics as AMI."
  },
  'MLT-3': {
    explanation: "Multi-Level Transmit 3 (MLT-3) uses three voltage levels (-V, 0, +V). It cycles through the levels in a specific order: 0, +V, 0, -V. A bit '1' causes a transition to the next level in the sequence, while a bit '0' causes no transition.",
    generation: "If data is '0', stay at current level. If data is '1', transition to the next state in the sequence (0 -> +V -> 0 -> -V -> 0).",
    applications: "Used in 100BASE-TX Ethernet over copper wiring.",
    insights: "Reduces the required bandwidth significantly (to 1/4 the baud rate) compared to NRZ, making it suitable for high-speed transmission over standard cables.",
    mistakes: "Forgetting the sequence. It's not a simple toggle; it must step through the 4-state cycle.",
    takeaways: "1 = Transition, 0 = No Transition. Sequence: 0, +V, 0, -V. Very low bandwidth."
  },
  '2B1Q': {
    explanation: "2 Binary 1 Quaternary (2B1Q) is a multilevel encoding scheme that takes 2 binary bits (a dibit) and converts them into 1 quaternary (4-level) symbol.",
    generation: "Pairs of bits are mapped to one of four voltage levels. For example: 00 -> -3V, 01 -> -1V, 10 -> +3V, 11 -> +1V (standard mappings may vary).",
    applications: "Used in ISDN U-interface and HDSL.",
    insights: "Transmits two bits per symbol, effectively halving the required bandwidth. However, it requires a higher signal-to-noise ratio to distinguish between the four voltage levels.",
    mistakes: "Processing one bit at a time. 2B1Q processes bits in pairs.",
    takeaways: "2 bits = 1 symbol. 4 voltage levels. High data rate in low bandwidth, but more susceptible to noise."
  }
};
